import{i as l}from"./assets/vendor-I1I71QQ2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();const d={method:"POST",headers:{"Content-Type":"application/json"}},u=async t=>{d.body=JSON.stringify(t);try{const e=await fetch("https:portfolio-js.b.goit.study/api/requests",d);if(!e.ok)throw new Error(e.status);return e.json()}catch(e){throw console.log(e),e}},m=(t,e)=>{let r;return function(...n){clearTimeout(r),r=setTimeout(()=>t.apply(this,n),e)}},p=t=>l.warning({message:t,position:"topRight",backgroundColor:"#e74a3b",messageColor:"#FAFAFB",messageLineHeight:"24px",maxWidth:"310px",theme:"dark"}),g=(t,e,r)=>{const n=`
  <div class="modal">
    <button class="modal-btn-close" data-modal-close>
      <svg class="modal-close" width="24" height="24">
        <use href="../img/icons-sprite.svg#close-modal"></use>
      </svg>
    </button>
    <h3 class="modal-title">${e}</h3>
    <p class="modal-text">
      ${r}
    </p>
  </div>`;t.innerHTML=n},a={contactForm:document.querySelector(".contact-form"),backDrop:document.querySelector(".backdrop"),errorMessage:document.querySelector(".notvalid")},c=()=>a.backDrop.classList.toggle("is-hidden"),f=()=>{const t=document.querySelector("[data-modal-close]");c();const e=r=>{(r.code==="Escape"||r.currentTarget===r.target)&&(c(),window.removeEventListener("keydown",e))};window.addEventListener("keydown",e),a.backDrop.addEventListener("click",e),t.addEventListener("click",c)},h=t=>{t.preventDefault();const{email:{value:e},comment:{value:r}}=t.target;u({email:e,comment:r}).then(({title:n,message:o})=>{g(a.backDrop,n,o),f(),t.target.reset()}).catch(n=>{p(`Error: № ${n.message}. Please verify the information you provided and try again `)})},y=m(t=>{const{valid:e}=t.target.validity;e?(a.errorMessage.classList.add("is-hidden"),t.target.classList.remove("notvalid")):(a.errorMessage.classList.remove("is-hidden"),t.target.classList.add("notvalid"))},2e3);a.contactForm.email.addEventListener("input",y);a.contactForm.addEventListener("submit",h);
//# sourceMappingURL=index.js.map
